In [2]:
import numpy as np

In [3]:
five = np.array([5,5,5])

In [4]:
five

array([5, 5, 5])

In [5]:
ones = np.ones(3)

In [6]:
ones

array([1., 1., 1.])

In [7]:
product = five*ones
product

array([5., 5., 5.])

In [8]:
multidim = np.array([[1,1,1],[2,2,2],[3,3,3]])
multidim

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [9]:
np.append(multidim, [4,4,4])                

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [10]:
np.arange(4)

array([0, 1, 2, 3])

In [75]:
a = np.ones(3)       #(3,1)  #All one dimensional vector are treated a column vector in this function
b = np.zeros((3,4))  #(3,4)

            
b.shape                      #returns dimension of array

(3, 4)

In [76]:
np.c_[a,b]                   #It concatenates your first array into the last dimension (axis) of the last array
                             # (3,1) + (3,4)  ---> (3, 4 + 1)  = (3,5)

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [77]:
b.ndim                       #Returns rank (the total number of dimensions). In this case b has 2 (x and y)

2

In [80]:
c = np.array([2,1])          #Can also make an array into a column vector
np.c_[c]


array([[2],
       [1]])